name: effect1d
channels:
    - https://repo.mamba.pm/emscripten-forge
    - conda-forge
dependencies:
    - xeus-python
    - ipywidgets==8.1.5
    - numpy==2.2.1
    - pip:
       - matplotlib==3.10.0
       - scikit-image==0.25.0
       - rft1d==0.2.3

