name: effect1d
channels:
    - https://repo.mamba.pm/emscripten-forge
    - conda-forge
dependencies:
    - xeus-python
    - ipywidgets
    - numpy==1.26.4
    - matplotlib
    - pip:
       - shapely==1.7.1
       - rft1d
