name: effect1d
channels:
    - https://repo.mamba.pm/emscripten-forge
    - conda-forge
dependencies:
    - xeus-python
    - ipywidgets==8.1.5
    - numpy==2.2.1
    - matplotlib
    - scikit-image
    - pip:
       - rft1d==0.2.3

