name: effect1d
channels:
    - https://repo.mamba.pm/emscripten-forge
    - conda-forge
dependencies:
    - xeus-python
    - ipywidgets
    - numpy==1.25.2
    - matplotlib
    - pygeos
    - shapely
    - pip:
       - rft1d
